/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop.main;

import desktop.java.Java;
import java.awt.Color;

/**
 *
 * @author alunoead
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setTitle("Inicio");
        setSize(400, 400);
        setResizable(false);
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonLinguagens = new javax.swing.JButton();
        ButtonConfiguracoes = new javax.swing.JButton();
        ButtonSite = new javax.swing.JButton();
        ButtonSair = new javax.swing.JButton();
        ButtonInformacoes = new javax.swing.JButton();
        LabelIcon = new javax.swing.JLabel();
        LabelBoasVindas = new javax.swing.JLabel();
        LabelUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));
        setSize(new java.awt.Dimension(300, 300));

        ButtonLinguagens.setBackground(new java.awt.Color(88, 63, 105));
        ButtonLinguagens.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        ButtonLinguagens.setText("Minhas linguagens");
        ButtonLinguagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLinguagensActionPerformed(evt);
            }
        });

        ButtonConfiguracoes.setBackground(new java.awt.Color(88, 63, 105));
        ButtonConfiguracoes.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        ButtonConfiguracoes.setText("Configurações da conta");
        ButtonConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfiguracoesActionPerformed(evt);
            }
        });

        ButtonSite.setBackground(new java.awt.Color(88, 63, 105));
        ButtonSite.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        ButtonSite.setText("Ir para o site");
        ButtonSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSiteActionPerformed(evt);
            }
        });

        ButtonSair.setBackground(new java.awt.Color(88, 63, 105));
        ButtonSair.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        ButtonSair.setText("Sair");
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });

        ButtonInformacoes.setBackground(new java.awt.Color(88, 63, 105));
        ButtonInformacoes.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        ButtonInformacoes.setText("Informações do programa");
        ButtonInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInformacoesActionPerformed(evt);
            }
        });

        LabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/imagens/icon.png"))); // NOI18N

        LabelBoasVindas.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LabelBoasVindas.setText("Bem-vindo, Okarin");

        LabelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/imagens/user.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBoasVindas)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(LabelUser))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonInformacoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonConfiguracoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonLinguagens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelIcon)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(LabelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelBoasVindas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonSite, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonLinguagens, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(ButtonInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLinguagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLinguagensActionPerformed
        // TODO add your handling code here:
        // chamando a janela java

        Java j = new Java();
        j.setVisible(true);
    }//GEN-LAST:event_ButtonLinguagensActionPerformed

    private void ButtonConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfiguracoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonConfiguracoesActionPerformed

    private void ButtonSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSiteActionPerformed

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonSairActionPerformed

    private void ButtonInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInformacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonInformacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConfiguracoes;
    private javax.swing.JButton ButtonInformacoes;
    private javax.swing.JButton ButtonLinguagens;
    private javax.swing.JButton ButtonSair;
    private javax.swing.JButton ButtonSite;
    private javax.swing.JLabel LabelBoasVindas;
    private javax.swing.JLabel LabelIcon;
    private javax.swing.JLabel LabelUser;
    // End of variables declaration//GEN-END:variables
}
