/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop.help;

import desktop.login.Entrar;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;

/**
 *
 * @author alunoead
 */
public class Ajuda extends javax.swing.JFrame {

    /**
     * Creates new form Ajuda
     */
    public Ajuda() {
        setUndecorated(true);
        initComponents();
        setSize(500, 300);
        setLocationRelativeTo(null);
        setTitle("Ajuda");
        setResizable(false);
        setDefaultCloseOperation(Ajuda.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAjuda = new javax.swing.JPanel();
        LabelUsuario = new javax.swing.JLabel();
        LabelCriador = new javax.swing.JLabel();
        LabelSenha = new javax.swing.JLabel();
        LabelTexto = new javax.swing.JLabel();
        LabelTexto2 = new javax.swing.JLabel();
        LabelTexto3 = new javax.swing.JLabel();
        LabelSite = new javax.swing.JLabel();
        LabelSair = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAjuda.setBackground(new java.awt.Color(255, 255, 255));
        PanelAjuda.setForeground(new java.awt.Color(103, 79, 117));

        LabelUsuario.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(103, 79, 117));
        LabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUsuario.setText("Usuário padrão: 0");

        LabelCriador.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LabelCriador.setForeground(new java.awt.Color(103, 79, 117));
        LabelCriador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCriador.setText("Criador: Okarin e Julio");

        LabelSenha.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LabelSenha.setForeground(new java.awt.Color(103, 79, 117));
        LabelSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSenha.setText("Senha padrão: 0");

        LabelTexto.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LabelTexto.setForeground(new java.awt.Color(103, 79, 117));
        LabelTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTexto.setText("Você não pode criar uma conta nesta versão");

        LabelTexto2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LabelTexto2.setForeground(new java.awt.Color(103, 79, 117));
        LabelTexto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTexto2.setText("para tal, voce precisa se registrar na");

        LabelTexto3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LabelTexto3.setForeground(new java.awt.Color(103, 79, 117));
        LabelTexto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTexto3.setText("versão web deste mesmo projeto");

        LabelSite.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LabelSite.setForeground(new java.awt.Color(103, 79, 117));
        LabelSite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSite.setText("elixitcc.000webhostapp.com");
        LabelSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelSiteMouseClicked(evt);
            }
        });

        LabelSair.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        LabelSair.setForeground(new java.awt.Color(103, 79, 117));
        LabelSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSair.setText("X");
        LabelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelAjudaLayout = new javax.swing.GroupLayout(PanelAjuda);
        PanelAjuda.setLayout(PanelAjudaLayout);
        PanelAjudaLayout.setHorizontalGroup(
            PanelAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAjudaLayout.createSequentialGroup()
                .addGroup(PanelAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTexto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAjudaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelTexto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelCriador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAjudaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PanelAjudaLayout.setVerticalGroup(
            PanelAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAjudaLayout.createSequentialGroup()
                .addGroup(PanelAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelUsuario))
                .addGap(1, 1, 1)
                .addComponent(LabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelTexto)
                .addGap(4, 4, 4)
                .addComponent(LabelTexto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSite, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCriador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(PanelAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelSiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSiteMouseClicked
        // TODO add your handling code here:
        String url = "http://elixirtcc.000webhostapp.com/registrar";

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        } else {
            Runtime runtime = Runtime.getRuntime();
            try {
                runtime.exec("xdg-open " + url);
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_LabelSiteMouseClicked

    private void LabelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCriador;
    private javax.swing.JLabel LabelSair;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LabelSite;
    private javax.swing.JLabel LabelTexto;
    private javax.swing.JLabel LabelTexto2;
    private javax.swing.JLabel LabelTexto3;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel PanelAjuda;
    // End of variables declaration//GEN-END:variables
}
