/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import desktop.Carregamento;

/**
 *
 * @author alunoead
 */
public class Entrar extends javax.swing.JFrame {

    /**
     * Creates new form Entrar
     */
    public Entrar() {
        initComponents();
        setTitle("Entrar");
        setSize(400,400);
        setResizable(false);
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonAjuda = new javax.swing.JButton();
        TextUsuario = new javax.swing.JTextField();
        LabelVersao = new javax.swing.JLabel();
        PasswordSenha = new javax.swing.JPasswordField();
        ButtonEntrar = new javax.swing.JButton();
        LabelIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        setMaximumSize(new java.awt.Dimension(250, 250));
        setMinimumSize(new java.awt.Dimension(250, 250));
        setName(""); // NOI18N
        setSize(new java.awt.Dimension(250, 250));

        ButtonAjuda.setBackground(new java.awt.Color(88, 63, 105));
        ButtonAjuda.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        ButtonAjuda.setText("Ajuda");
        ButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjudaActionPerformed(evt);
            }
        });

        TextUsuario.setBackground(new java.awt.Color(103, 79, 117));
        TextUsuario.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        TextUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextUsuario.setText("Usuário");
        TextUsuario.setName(""); // NOI18N
        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });

        LabelVersao.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        LabelVersao.setText("Versão: 0.01");

        PasswordSenha.setBackground(new java.awt.Color(103, 79, 117));
        PasswordSenha.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        PasswordSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordSenha.setText("Senha");

        ButtonEntrar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonEntrar.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        ButtonEntrar.setText("Entrar");
        ButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEntrarActionPerformed(evt);
            }
        });

        LabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/imagens/icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelVersao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAjuda))
                    .addComponent(TextUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordSenha)
                    .addComponent(ButtonEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(LabelIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LabelIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjudaActionPerformed
        // TODO add your handling code here:
        // chamando a janela ajuda
        
        Ajuda a = new Ajuda();
        a.setVisible(true);
        
    }//GEN-LAST:event_ButtonAjudaActionPerformed

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void ButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEntrarActionPerformed
        // TODO add your handling code here:
        String usuario = TextUsuario.getText();
        String senha = PasswordSenha.getText();
        
        if(senha.contains("0") && (usuario.contains("0"))){
            TextUsuario.setText(null);
            PasswordSenha.setText(null);
            systemExit();
            
            Carregamento c = new Carregamento();
            c.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Não foi possível realizar o login", "Erro", JOptionPane.ERROR_MESSAGE);
            TextUsuario.setText(null);
            PasswordSenha.setText(null);
        }
    }//GEN-LAST:event_ButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAjuda;
    private javax.swing.JButton ButtonEntrar;
    private javax.swing.JLabel LabelIcon;
    private javax.swing.JLabel LabelVersao;
    private javax.swing.JPasswordField PasswordSenha;
    private javax.swing.JTextField TextUsuario;
    // End of variables declaration//GEN-END:variables

    private void systemExit(){
        WindowEvent winCloseing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }

}
