/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop.java;

import desktop.main.Inicio;

/**
 *
 * @author alunoead
 */
public class Java extends javax.swing.JFrame {

    /**
     * Creates new form Java
     */
    public Java() {
        setUndecorated(true);
        initComponents();
        setSize(1000, 600);
        setLocationRelativeTo(null);
        setTitle("Java");
        setResizable(false);
        setDefaultCloseOperation(Inicio.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelCapitulo5 = new javax.swing.JLabel();
        LabelCapitulo1 = new javax.swing.JLabel();
        LabelCapitulo4 = new javax.swing.JLabel();
        LabelCapitulo3 = new javax.swing.JLabel();
        LabelCapitulo2 = new javax.swing.JLabel();
        LabelJava2 = new javax.swing.JLabel();
        LabelImagemEsquerda = new javax.swing.JLabel();
        PanelJava = new javax.swing.JPanel();
        LabelJava = new javax.swing.JLabel();
        LabelTexto = new javax.swing.JLabel();
        LabelTexto2 = new javax.swing.JLabel();
        LabelTexto3 = new javax.swing.JLabel();
        LabelTexto4 = new javax.swing.JLabel();
        LabelTexto5 = new javax.swing.JLabel();
        LabelTexto6 = new javax.swing.JLabel();
        LabelTexto7 = new javax.swing.JLabel();
        LabelTexto8 = new javax.swing.JLabel();
        LabelTexto9 = new javax.swing.JLabel();
        LabelTexto10 = new javax.swing.JLabel();
        LabelSair = new javax.swing.JLabel();
        LabelVoltar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        setMinimumSize(new java.awt.Dimension(300, 300));
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCapitulo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/image/cap-5.png"))); // NOI18N
        getContentPane().add(LabelCapitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        LabelCapitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/image/cap-1.png"))); // NOI18N
        getContentPane().add(LabelCapitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        LabelCapitulo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/image/cap-4.png"))); // NOI18N
        getContentPane().add(LabelCapitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        LabelCapitulo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/image/cap-3.png"))); // NOI18N
        getContentPane().add(LabelCapitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        LabelCapitulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/image/cap-2.png"))); // NOI18N
        getContentPane().add(LabelCapitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        LabelJava2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJava2.setIcon(new javax.swing.ImageIcon("C:\\Users\\archwinlinu\\Desktop\\icons\\icons-colorido\\java.png")); // NOI18N
        getContentPane().add(LabelJava2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 400, 150));

        LabelImagemEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/image/fundo.jpg"))); // NOI18N
        LabelImagemEsquerda.setText("jLabel10");
        getContentPane().add(LabelImagemEsquerda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        PanelJava.setBackground(new java.awt.Color(255, 255, 255));

        LabelJava.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        LabelJava.setForeground(new java.awt.Color(103, 79, 117));
        LabelJava.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop/image/java.png"))); // NOI18N

        LabelTexto.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LabelTexto.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTexto.setText("Bem-vindo a sessão de exercício do Java!");

        LabelTexto2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LabelTexto2.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTexto2.setText("> Cada capítulo possui uma média de 30 á 50 exercícios.");

        LabelTexto3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LabelTexto3.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTexto3.setText("> O Seu progresso é salvo toda vez que voce sai de um capítulo");

        LabelTexto4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LabelTexto4.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTexto4.setText("> Mas as suas respostas não (acontece :D)");

        LabelTexto5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LabelTexto5.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTexto5.setText("> Segue conteúdo de cada capítulo:");

        LabelTexto6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LabelTexto6.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTexto6.setText("Capítulo 1: Aprofundando-se no Java, introdução ao mundo Java");

        LabelTexto7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LabelTexto7.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTexto7.setText("Capítulo 2: Java com orientação a objeto");

        LabelTexto8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LabelTexto8.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTexto8.setText("Capítulo 3: Bibliotecas do Java");

        LabelTexto9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LabelTexto9.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTexto9.setText("Capítulo 4: Java Coleções (Collections)");

        LabelTexto10.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LabelTexto10.setForeground(new java.awt.Color(222, 56, 38));
        LabelTexto10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTexto10.setText("Capítulo 5: Serverlets e Maven (Java Web)");

        LabelSair.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        LabelSair.setForeground(new java.awt.Color(103, 79, 117));
        LabelSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSair.setText("X");
        LabelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelSairMouseClicked(evt);
            }
        });

        LabelVoltar.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        LabelVoltar.setForeground(new java.awt.Color(103, 79, 117));
        LabelVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelVoltar.setText("<");
        LabelVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelJavaLayout = new javax.swing.GroupLayout(PanelJava);
        PanelJava.setLayout(PanelJavaLayout);
        PanelJavaLayout.setHorizontalGroup(
            PanelJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelJavaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTexto6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTexto7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTexto8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTexto9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTexto10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJavaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelTexto5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelTexto4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelTexto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelTexto3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJavaLayout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addGroup(PanelJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJavaLayout.createSequentialGroup()
                        .addComponent(LabelJava, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PanelJavaLayout.setVerticalGroup(
            PanelJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJavaLayout.createSequentialGroup()
                .addGroup(PanelJavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJava, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto)
                .addGap(18, 18, 18)
                .addComponent(LabelTexto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto5)
                .addGap(18, 18, 18)
                .addComponent(LabelTexto6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(LabelVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(PanelJava, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelSairMouseClicked

    private void LabelVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVoltarMouseClicked
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
    }//GEN-LAST:event_LabelVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCapitulo1;
    private javax.swing.JLabel LabelCapitulo2;
    private javax.swing.JLabel LabelCapitulo3;
    private javax.swing.JLabel LabelCapitulo4;
    private javax.swing.JLabel LabelCapitulo5;
    private javax.swing.JLabel LabelImagemEsquerda;
    private javax.swing.JLabel LabelJava;
    private javax.swing.JLabel LabelJava2;
    private javax.swing.JLabel LabelSair;
    private javax.swing.JLabel LabelTexto;
    private javax.swing.JLabel LabelTexto10;
    private javax.swing.JLabel LabelTexto2;
    private javax.swing.JLabel LabelTexto3;
    private javax.swing.JLabel LabelTexto4;
    private javax.swing.JLabel LabelTexto5;
    private javax.swing.JLabel LabelTexto6;
    private javax.swing.JLabel LabelTexto7;
    private javax.swing.JLabel LabelTexto8;
    private javax.swing.JLabel LabelTexto9;
    private javax.swing.JLabel LabelVoltar;
    private javax.swing.JPanel PanelJava;
    // End of variables declaration//GEN-END:variables
}
